name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
         echo "${{ secrets.PRATIK }}" | docker login -u "7038688876" --password-stdin
         docker image build -t 7038688876/flaskapp:v1 .
         docker push 7038688876/flaskapp:v1 
      
      
      
      
